spring.application.name=primo-progetto

server.port=8081
management.endpoints.web.exposure.include=*

app.nome=Academy App
app.versione=1.0.0
app.messaggio-benvenuto=Benvenuto nella nostra applicazione!

spring.profiles.active=dev
